// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV2qEsT3fmWll4BUbmXSIOCKbL9qAnXBo',
    appId: '1:1002646272192:android:e187c9c7c70995d107d525',
    messagingSenderId: '1002646272192',
    projectId: 'financewrapped',
    storageBucket: 'financewrapped.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoU7mfv9hIh926eA6Ig3sJALUMmvjmge4',
    appId: '1:1002646272192:web:d4df53742e8ad5f407d525',
    messagingSenderId: '1002646272192',
    projectId: 'financewrapped',
    authDomain: 'financewrapped.firebaseapp.com',
    storageBucket: 'financewrapped.firebasestorage.app',
    measurementId: 'G-9GKSX1KNVE',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoU7mfv9hIh926eA6Ig3sJALUMmvjmge4',
    appId: '1:1002646272192:web:d4df53742e8ad5f407d525',
    messagingSenderId: '1002646272192',
    projectId: 'financewrapped',
    authDomain: 'financewrapped.firebaseapp.com',
    storageBucket: 'financewrapped.firebasestorage.app',
    measurementId: 'G-9GKSX1KNVE',
  );
}
